baseurl = "https://example.com"
title = "Hugo Theme"
author = "@JeffProd"
copyright = "Copyright © 2008–2018, @JeffProd"
canonifyurls = true
paginate = 3
publishDir = "C:\Users\Owner\Google Drive\Other\dilernia.gitub.io"

theme = "hugo-blog-jeffprod"

[taxonomies]
    tag = "tags"
    archive = "archives"
